language: d

sudo: required
dist: bionic

d:
  - dmd
  - ldc

os:
  - linux
  - osx

script:
  - dub test --compiler=${DC}
  - dub test --compiler=${DC} -c simple
  - dub build --compiler=${DC} -b plain -c rich
  - dub build --compiler=${DC} -b plain -c twitch
  - dub build --compiler=${DC} -b plain -c simple
  - dub build --compiler=${DC} -b release -c rich
  - dub build --compiler=${DC} -b release -c twitch
  - dub build --compiler=${DC} -b release -c simple
  - test ${DC} = ldc2 || dub build --compiler=${DC} -b ddox

before_deploy:
  - cp -rv .circleci docs/

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
    condition:
      - ${DC} = dmd
      - ${TRAVIS_OS_NAME} = linux
  cache:
    directories:
      - $HOME/.dub
  verbose: true
