language: d

sudo: required
dist: focal

branches:
  except:
    - /appveyor-.*/
    - /circleci-.*/
    - gh-pages
    - /dustmite-.*/
    - /github-.*/

d:
  - dmd
  - ldc

os:
  - linux
  - osx

script:
  #- git clone https://github.com/zorael/lu.git
  #- dub add-local lu
  - dub test  --compiler=${DC}
  - dub build --compiler=${DC} -b debug
  - dub build --compiler=${DC} -b debug -c dev
  - dub build --compiler=${DC} -b plain
  - dub build --compiler=${DC} -b plain -c dev
  - dub build --compiler=${DC} -b release
  - dub build --compiler=${DC} -b release -c dev
  - dub build --compiler=${DC} -b debug :assertgen
