name: D

on:
  push:
    branches-ignore:
      - travis-*
      - circleci-*
      - appveyor-*
      - dustmite-*
      - gh-pages

  pull_request:
    branches-ignore:
      - travis-*
      - circleci-*
      - appveyor-*
      - dustmite-*
      - gh-pages

jobs:
  build:
    name: 'Everything'
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        dc: [ dmd-latest, dmd-2.108.0, ldc-latest, ldc-1.38.0 ]

    runs-on: ${{ matrix.os }}
    continue-on-error: false
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: 'Install D compiler'
      uses: dlang-community/setup-dlang@v2
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Run tests'
      run: dub test

    - name: 'Build: library'
      run: |
        dub build --nodeps -b debug   -c library
        dub build --nodeps -b release -c library

    - name: 'Build: twitch'
      run: |
        dub build --nodeps -b debug   -c twitch
        dub build --nodeps -b release -c twitch

    - name: 'Build: dev'
      run: |
        dub build --nodeps -b debug   -c dev
        dub build --nodeps -b release -c dev

    - name: 'Build: assertgen'
      run: dub build --nodeps -b debug :assertgen

    - name: 'Build: docs'
      if: matrix.dc == 'dmd-latest' && matrix.os == 'ubuntu-latest' && success()
      run : dub build --nodeps -b docs

    - name: 'Generate documenation'
      if: matrix.dc == 'dmd-latest' && matrix.os == 'ubuntu-latest' && success()
      run: |
        git clone https://github.com/zorael/lu.git
        dub fetch adrdox
        dub run adrdox -- -ip --header-title="dialect IRC parser" source lu/source
        cp -rv .circleci generated-docs

    - name: 'Deploy documentation to GitHub Pages'
      if: matrix.dc == 'dmd-latest' && matrix.os == 'ubuntu-latest' && success()
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        target_branch: gh-pages
        keep_history: false
        allow_empty_commit: true
        build_dir: generated-docs
